Repository medik8s/machine-deletion-remediation, pull requests merged in 2023-03, with the labels that each got.

#45 Add scorecard definitions and make test pass
  api/v1alpha1/machinedeletionremediation_types.go
  api/v1alpha1/machinedeletionremediationtemplate_types.go
  bundle/manifests/machine-deletion-remediation.clusterserviceversion.yaml
  bundle/manifests/machine-deletion-remediation.medik8s.io_machinedeletionremediationtemplates.yaml
  bundle/tests/scorecard/config.yaml
  config/crd/bases/machine-deletion-remediation.medik8s.io_machinedeletionremediationtemplates.yaml
  config/manifests/bases/machine-deletion-remediation.clusterserviceversion.yaml
  config/samples/machine-deletion-remediation_v1alpha1_machinedeletionremediation.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
Labels: approved, lgtm

#47 Set bundle fields containerImage and createdAt in Makefile
  Makefile
Labels: approved, lgtm

#46 Add short names for CRDs
  api/v1alpha1/machinedeletionremediation_types.go
  api/v1alpha1/machinedeletionremediationtemplate_types.go
  bundle/manifests/machine-deletion-remediation.medik8s.io_machinedeletionremediations.yaml
  bundle/manifests/machine-deletion-remediation.medik8s.io_machinedeletionremediationtemplates.yaml
  config/crd/bases/machine-deletion-remediation.medik8s.io_machinedeletionremediations.yaml
  config/crd/bases/machine-deletion-remediation.medik8s.io_machinedeletionremediationtemplates.yaml
Labels: approved, lgtm

#48 Fix Error flow flaky test
  controllers/machinedeletionremediation_controller_test.go
Labels: approved, lgtm

#49 Fix PodSecurity "restricted" warning
  bundle/manifests/machine-deletion-remediation.clusterserviceversion.yaml
  config/default/kustomization.yaml
  config/manager/manager.yaml
Labels: approved, lgtm

#50 Align MDR makefile
  Makefile
  controllers/machinedeletionremediation_controller.go
  controllers/machinedeletionremediation_controller_test.go
  controllers/suite_test.go
  e2e/e2e_suite_test.go
  e2e/e2e_test.go
  main.go
Labels: approved, lgtm, do-not-merge/hold

#52 Improve operator description in bundle
  bundle/manifests/machine-deletion-remediation.clusterserviceversion.yaml
  config/manifests/bases/machine-deletion-remediation.clusterserviceversion.yaml
Labels: approved, lgtm

#53 Improve reconcile logging
  controllers/machinedeletionremediation_controller.go
  main.go
Labels: approved, do-not-merge/hold

#54 Add bundle-run Makefile target
  Makefile
Labels: approved, lgtm

#56 Set minKubeVersion
  bundle/manifests/machine-deletion-remediation.clusterserviceversion.yaml
  config/manifests/bases/machine-deletion-remediation.clusterserviceversion.yaml
Labels: approved, lgtm

#55 Extend Bundle Validation with bundle-validate Target
  Makefile
Labels: approved, lgtm
